export default {
  id: 19947,
  uri: "/api/audiobooks/19947/",
  slug: "bogatyi-papa-bednyi-papa",
  name: "Богатый папа, бедный папа",
  main_author: {
    id: 1452,
    uri: "/api/authors/1452/",
    slug: "robert-toru-kiiosaki",
    cover_name: "Роберт Тору Кийосаки",
    web_url: "https://zvukislov.ru/author/1452-robert-toru-kiiosaki/",
    photo:
      "https://zvukislov.ru/c/330x330/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
    image:
      "https://zvukislov.ru/storage/public/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
    default_image:
      "https://zvukislov.ru/storage/public/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
    first_name: "Роберт",
    last_name: "Кийосаки",
    genitive_full_name: "Роберта Кийосаки",
    book_count: 11,
    created_at: "2015-09-15T19:34:13Z",
    updated_at: "2019-04-08T12:11:04Z",
    description: "",
  },
  image:
    "https://zvukislov.ru/storage/public/book_covers/68/85/6885dcbf-91bd-32b6-ba70-842a177b8af6.jpg",
  default_image:
    "https://zvukislov.ru/storage/public/book_covers/9c/9e/9c9e9e49-9b2d-3805-aaf4-a6b0e7bb1992.jpg",
  web_url: "https://zvukislov.ru/books/19947-bogatyi-papa-bednyi-papa/",
  active: true,
  cover:
    "https://zvukislov.ru/c/330x330/book_covers/68/85/6885dcbf-91bd-32b6-ba70-842a177b8af6.jpg",
  seconds: 20984,
  cover_color: "ffffff",
  series: [
    {
      id: 10525,
      series: {
        id: 772,
        uri: "/api/series/772/",
        name: "Богатый Папа",
        image:
          "https://zvukislov.ru/storage/public/series_covers/ed1fa28b-cdb3-3c1d-aab4-74e84161be68_LvwkWfK.png",
        default_image:
          "https://zvukislov.ru/storage/public/series_covers/ed1fa28b-cdb3-3c1d-aab4-74e84161be68_LvwkWfK.png",
        square_image:
          "https://zvukislov.ru/storage/public/series_covers/485f24f8-2084-3edf-82cc-7d4a13f6c5ce_m8Hljd6.png",
        created_at: "2015-09-27T16:44:14Z",
        updated_at: "2019-04-09T12:00:18Z",
        book_count: 7,
        web_url: "https://zvukislov.ru/series/772-bogatyi-papa/",
        type: "audiobook",
      },
      order: 0,
    },
  ],
  main_actor: {
    id: 2467,
    uri: "/api/actors/2467/",
    slug: "denis-garmash",
    cover_name: "Денис Гармаш",
    web_url: "https://zvukislov.ru/actor/2467-denis-garmash/",
    photo: null,
    image: null,
    default_image:
      "https://zvukislov.ru/storage/public/null/default_book_cover.jpg",
    genitive_full_name: "Дениса Гармаша",
    book_count: 15,
    created_at: "2015-09-27T16:30:20Z",
    updated_at: "2019-05-13T15:08:16Z",
  },
  created_at: "2016-10-14T15:03:32Z",
  reviews_rating: 4.33384379785605,
  reviews_count: 1959,
  user_rating: null,
  global_rating: 1.125,
  background_color: "f3c33b",
  font_color: "070505",
  link_color: "835370",
  square_cover: "book_covers/9c/9e/9c9e9e49-9b2d-3805-aaf4-a6b0e7bb1992.jpg",
  order: null,
  type: "audiobook",
  updated_at: "2019-04-09T00:32:36Z",
  written_at: "2014-01-01",
  released_at: "2014-10-29",
  language: "ru",
  annotation:
    "Бестселлер №1 в мире «Богатый папа, бедный папа»! Уникальную аудиокнигу Роберта Кийосаки в России представляет издательство AB Publishing!\n\nРоберт Кийосаки убежден в том, что современная система школьного образования не дает действительно нужных для жизни знаний – знаний о деньгах. Все это приводит к тому, что мы вынуждены всю жизнь работать за деньги и зарабатывать их для других. И это вместо того, чтобы заставить работать деньги на себя!\n\nВ центре книги – история самого Кийосаки. Его воспитывали два папы. Один – бедный – государственный служащий, второй – богатый – бизнесмен, ставший одним из самых влиятельных людей на Гавайских островах. Маленький Роберт выбрал путь, предложенный Богатым папой, и добился того, что стал финансово обеспеченным человеком. И теперь он готов делиться секретами своего успеха. А они работают, ведь неслучайно его бестселлер считают обязательным чтением для миллионеров!\n\nПрослушав эту книгу, вы узнаете:\n\n– С чего начать свой путь к процветанию.\n\n– Как изменить свое отношение к деньгам;\n\n– Какой путь приумножения богатства выбрать;\n\n– Как заставить работать деньги на себя;\n\n– Что такое активы и пассивы и какова их роль в приумножении денег;\n\n«Богатый папа, бедный папа» – прослушав эту книгу, вы захотите изменить свою жизнь!",
  html_annotation:
    '<p>Бестселлер №1 в мире «Богатый папа, бедный папа»! Уникальную аудиокнигу Роберта Кийосаки в России представляет издательство AB Publishing!</p><p>Роберт Кийосаки убежден в том, что современная система школьного образования не дает действительно нужных для жизни знаний – знаний о деньгах. Все это приводит к тому, что мы вынуждены всю жизнь работать за деньги и зарабатывать их для других. И это вместо того, чтобы заставить работать деньги на себя!</p><p>В центре книги – история самого Кийосаки. Его воспитывали два папы. Один – бедный – государственный служащий, второй – богатый – бизнесмен, ставший одним из самых влиятельных людей на Гавайских островах. Маленький Роберт выбрал путь, предложенный Богатым папой, и добился того, что стал финансово обеспеченным человеком. И теперь он готов делиться секретами своего успеха. А они работают, ведь неслучайно его бестселлер считают обязательным чтением для миллионеров!</p><p>Прослушав эту книгу, вы узнаете:</p><p>–&#160;С чего начать свой путь к процветанию.</p><p>–&#160;Как изменить свое отношение к деньгам;</p><p>–&#160;Какой путь приумножения богатства выбрать;</p><p>–&#160;Как заставить работать деньги на себя;</p><p>–&#160;Что такое активы и пассивы и какова их роль в приумножении денег;</p><p>«Богатый папа, бедный папа» – прослушав эту книгу, вы захотите изменить свою жизнь!</p><p class="spoiler"><p>Введение</p><p>Урок 1. Богатые не работают за деньги</p><p>Урок 2. Зачем нужна финансовая грамотность</p><p>Урок 3. Занимайтесь собственным бизнесом</p><p>Урок 4. История подоходного налога и возможности корпораций</p><p>Урок 5. Богатые изобретают деньги</p><p>Урок 6. Работайте не за деньги, а ради опыта</p><p>Преодоление препятствий</p><p>С чего начать</p><p>Вам всё ещё мало? Вот несколько первоочередных дел</p><p>Заключительные мысли</p><p>Об авторе</p></p>',
  bytes: 165943582,
  authors: [
    {
      id: 1452,
      uri: "/api/authors/1452/",
      slug: "robert-toru-kiiosaki",
      cover_name: "Роберт Тору Кийосаки",
      web_url: "https://zvukislov.ru/author/1452-robert-toru-kiiosaki/",
      photo:
        "https://zvukislov.ru/c/330x330/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
      image:
        "https://zvukislov.ru/storage/public/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
      default_image:
        "https://zvukislov.ru/storage/public/author_photos/c1/e8/c1e88f87-475e-38c4-8a97-ba028fa53b7b.png",
      first_name: "Роберт",
      last_name: "Кийосаки",
      genitive_full_name: "Роберта Кийосаки",
      book_count: 11,
      created_at: "2015-09-15T19:34:13Z",
      updated_at: "2019-04-08T12:11:04Z",
      description: "",
    },
  ],
  actors: [
    {
      id: 2467,
      uri: "/api/actors/2467/",
      slug: "denis-garmash",
      cover_name: "Денис Гармаш",
      web_url: "https://zvukislov.ru/actor/2467-denis-garmash/",
      photo: null,
      image: null,
      default_image:
        "https://zvukislov.ru/storage/public/null/default_book_cover.jpg",
      genitive_full_name: "Дениса Гармаша",
      book_count: 15,
      created_at: "2015-09-27T16:30:20Z",
      updated_at: "2019-05-13T15:08:16Z",
    },
  ],
  publisher: {
    id: 131,
    uri: "/api/publishers/131/",
    name: "Аудиоагент «АВ Паблишинг»",
    created_at: "2015-09-27T16:43:40Z",
    updated_at: "2015-09-27T16:43:40Z",
  },
  rightholder: {
    id: 66,
    uri: "/api/rightholder/66/",
    name: "AB Publishing",
    web_url: "https://zvukislov.ru/rightholder/66-ab-publishing/",
  },
  genres: [
    {
      id: 856,
      uri: "/api/genres/856/",
      name: "Личные финансы",
      slug: "lichnye-finansy",
      niche: {
        id: 29,
        uri: "/api/niches/29/",
        name: "Бизнес-книги",
        slug: "biznes-knigi",
        book_count: 9556,
        order: 0,
        hide_genres: false,
        image: "https://zvukislov.ru/storage/public/niche_covers/2_.jpg",
        web_url: "https://zvukislov.ru/catalog/29-biznes-knigi/",
      },
      book_count: 53,
      web_url:
        "https://zvukislov.ru/catalog/29-biznes-knigi/856-lichnye-finansy/",
    },
    {
      id: 901,
      uri: "/api/genres/901/",
      name: "Просто о бизнесе",
      slug: "prosto-o-biznese",
      niche: {
        id: 29,
        uri: "/api/niches/29/",
        name: "Бизнес-книги",
        slug: "biznes-knigi",
        book_count: 9556,
        order: 0,
        hide_genres: false,
        image: "https://zvukislov.ru/storage/public/niche_covers/2_.jpg",
        web_url: "https://zvukislov.ru/catalog/29-biznes-knigi/",
      },
      book_count: 1173,
      web_url:
        "https://zvukislov.ru/catalog/29-biznes-knigi/901-prosto-o-biznese/",
    },
    {
      id: 1276,
      uri: "/api/genres/1276/",
      name: "Саморазвитие, личностный рост",
      slug: "samorazvitie-lichnostnyi-rost",
      niche: {
        id: 37,
        uri: "/api/niches/37/",
        name: "Книги по психологии",
        slug: "knigi-po-psikhologii",
        book_count: 10194,
        order: 0,
        hide_genres: false,
        image: "https://zvukislov.ru/storage/public/niche_covers/3_.jpg",
        web_url: "https://zvukislov.ru/catalog/37-knigi-po-psikhologii/",
      },
      book_count: 798,
      web_url:
        "https://zvukislov.ru/catalog/37-knigi-po-psikhologii/1276-samorazvitie-lichnostnyi-rost/",
    },
  ],
  files: [
    {
      id: 218646,
      uri: "/api/audiofiles/218646/",
      url: "/api/audiofiles/218646/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218646/file.mp3",
      seconds: 973,
      bytes: 7510917,
      title: "",
      order: 0,
    },
    {
      id: 218647,
      uri: "/api/audiofiles/218647/",
      url: "/api/audiofiles/218647/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218647/file.mp3",
      seconds: 3847,
      bytes: 29740769,
      title: "",
      order: 1,
    },
    {
      id: 218648,
      uri: "/api/audiofiles/218648/",
      url: "/api/audiofiles/218648/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218648/file.mp3",
      seconds: 2346,
      bytes: 18746245,
      title: "",
      order: 2,
    },
    {
      id: 218649,
      uri: "/api/audiofiles/218649/",
      url: "/api/audiofiles/218649/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218649/file.mp3",
      seconds: 929,
      bytes: 7419613,
      title: "",
      order: 3,
    },
    {
      id: 218650,
      uri: "/api/audiofiles/218650/",
      url: "/api/audiofiles/218650/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218650/file.mp3",
      seconds: 1344,
      bytes: 10698535,
      title: "",
      order: 4,
    },
    {
      id: 218651,
      uri: "/api/audiofiles/218651/",
      url: "/api/audiofiles/218651/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218651/file.mp3",
      seconds: 2827,
      bytes: 22129632,
      title: "",
      order: 5,
    },
    {
      id: 218652,
      uri: "/api/audiofiles/218652/",
      url: "/api/audiofiles/218652/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218652/file.mp3",
      seconds: 1792,
      bytes: 14377505,
      title: "",
      order: 6,
    },
    {
      id: 218653,
      uri: "/api/audiofiles/218653/",
      url: "/api/audiofiles/218653/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218653/file.mp3",
      seconds: 2250,
      bytes: 17871506,
      title: "",
      order: 7,
    },
    {
      id: 218654,
      uri: "/api/audiofiles/218654/",
      url: "/api/audiofiles/218654/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218654/file.mp3",
      seconds: 2976,
      bytes: 23818978,
      title: "",
      order: 8,
    },
    {
      id: 218655,
      uri: "/api/audiofiles/218655/",
      url: "/api/audiofiles/218655/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218655/file.mp3",
      seconds: 660,
      bytes: 5353050,
      title: "",
      order: 9,
    },
    {
      id: 218656,
      uri: "/api/audiofiles/218656/",
      url: "/api/audiofiles/218656/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218656/file.mp3",
      seconds: 915,
      bytes: 7266021,
      title: "",
      order: 10,
    },
    {
      id: 218657,
      uri: "/api/audiofiles/218657/",
      url: "/api/audiofiles/218657/file.mp3",
      absolute_url: "https://zvukislov.ru/api/audiofiles/218657/file.mp3",
      seconds: 125,
      bytes: 1010811,
      title: "",
      order: 11,
    },
  ],
  preview: {
    id: 218645,
    uri: "/api/audiofiles/218645/",
    url: "/api/audiofiles/218645/file.mp3",
    absolute_url: "https://zvukislov.ru/api/audiofiles/218645/file.mp3",
    seconds: 20984,
    bytes: 2728905,
    title: "",
    order: 0,
  },
  tags: [
    {
      id: 782,
      uri: "/api/tags/782/",
      name: "крысиные бега",
      web_url: "https://zvukislov.ru/catalog/books/?tag=782",
    },
  ],
  booksets: [
    {
      id: 528,
      uri: "/api/booksets/528/",
      name: "Топ аудиокниг за 2018 год",
      description:
        "Мы составили рейтинг лучших аудиокниг на основе прослушиваний в приложении «Звуки Слов» за прошедший год. Здесь бестселлеры по психологии Джона Кехо и Дейла Карнеги, лекции Михаила Лабковского, романтические истории Джоджо Мойес, научпоп Юваля Харари и детектив Ю Несбё. Послушайте то, что еще не успели!",
      is_visible: true,
      image:
        "https://zvukislov.ru/storage/public/bookset_images/cb92ed8b-9ba3-4c91-a0e7-9a90bf89b9c4.jpg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/cb92ed8b-9ba3-4c91-a0e7-9a90bf89b9c4.jpg",
      book_count: 18,
      published_at: "2018-12-21T16:46:19Z",
      created_at: "2018-12-06T14:17:22Z",
      updated_at: "2018-12-21T16:59:38Z",
      web_url: "https://zvukislov.ru/booksets/528-top-audioknig-za-2018-god/",
    },
    {
      id: 404,
      uri: "/api/booksets/404/",
      name: "Как добиться успеха",
      description:
        "Чтобы добиться успеха в любом деле, нужно много работать и верить в свои силы. Поднять самооценку, настроиться на победу вам помогут аудиокниги из этой подборки. Прислушайтесь к опыту мировых коучей Брайана Трейси, Наполеона Хилла, Дейла Карнеги и Роберта Кийосаки.",
      is_visible: true,
      image:
        "https://zvukislov.ru/storage/public/bookset_images/15506uYKAagsUhZmVNxiEbCJtwqOD.jpg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/15506uYKAagsUhZmVNxiEbCJtwqOD.jpg",
      book_count: 19,
      published_at: "2018-09-17T10:11:39Z",
      created_at: "2018-04-06T08:28:52Z",
      updated_at: "2019-04-03T09:20:30Z",
      web_url: "https://zvukislov.ru/booksets/404-kak-dobitsia-uspekha/",
    },
    {
      id: 471,
      uri: "/api/booksets/471/",
      name: "Лучшие книги по психологии",
      description:
        "Мы собрали лучшие аудиокниги по психологии в большую подборку, чтобы вы ничего не упустили. \r\nВключайте тренинги мировых специалистов Стивена Кови, Джона Кехо, Дейла Карнеги и Брайана Трейси. Не обделяйте вниманием советы отечественных психологов Андрея Курпатова, Михаила Лабковского и Юлии Гиппенрейтер. \r\nВы научитесь позитивному тайм-менеджменту, перестанете беспокоиться по пустякам, откроете в себе лидерские качества, избавитесь от ограничивающих установок. Приятного прослушивания!",
      is_visible: true,
      image:
        "https://zvukislov.ru/storage/public/bookset_images/3847217443-min.jpg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/3847217443-min.jpg",
      book_count: 38,
      published_at: "2018-08-21T07:59:57Z",
      created_at: "2018-08-21T07:59:59Z",
      updated_at: "2018-09-18T14:21:12Z",
      web_url:
        "https://zvukislov.ru/booksets/471-luchshie-knigi-po-psikhologii/",
    },
    {
      id: 251,
      uri: "/api/booksets/251/",
      name: "Топ аудиокниг за 2017 год",
      description:
        "В списке вы найдете зарубежную прозу Джоджо Мойес и Грегори Робертса, книги по психологии взаимоотношений, силе подсознания, русскую классику Михаила Булгакова и Сергея Довлатова. \r\nВозглавила список книга Дейла Карнеги об умении жить сегодняшним днем – «Как перестать беспокоиться и начать жить».  \r\nТоп составлен на основе прослушиваний аудиокниг в приложении «Звуки Слов» за прошедший год.",
      is_visible: true,
      image: "https://zvukislov.ru/storage/public/bookset_images/o-o.jpeg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/o-o.jpeg",
      book_count: 14,
      published_at: "2017-12-29T14:12:41Z",
      created_at: "2017-12-25T07:55:25Z",
      updated_at: "2017-12-29T14:12:49Z",
      web_url: "https://zvukislov.ru/booksets/251-top-audioknig-za-2017-god/",
    },
    {
      id: 67,
      uri: "/api/booksets/67/",
      name: "Секреты успеха выдающихся личностей",
      description:
        "В чем секрет богатства? Что такое психология достатка?\r\nПослушайте яркие цитаты и истории политических деятелей, бизнесменов и просто интересных личностей. Узнайте подробности о жизни и работе Дональда Трампа, Уинстона Черчилля, Генри Форда, Билла Гейтса, Авраама Линкольна и других выдающихся людей.",
      is_visible: true,
      image:
        "https://zvukislov.ru/storage/public/bookset_images/3019834-poster-p-1-the-most-important-idea-bill-gates-ever-had.jpg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/3019834-poster-p-1-the-most-important-idea-bill-gates-ever-had.jpg",
      book_count: 22,
      published_at: "2017-09-28T14:00:21Z",
      created_at: "2016-10-18T13:04:04Z",
      updated_at: "2018-05-15T07:23:08Z",
      web_url:
        "https://zvukislov.ru/booksets/67-sekrety-uspekha-vydaiushchikhsia-lichnostei/",
    },
    {
      id: 69,
      uri: "/api/booksets/69/",
      name: "Коллекция книг бизнес-гуру Роберта Кийосаки",
      description:
        "Практические материалы, советы, примеры, вопросы, упражнения, благодаря которым благие намерения превращаются в чёткие, достижимые цели. Роберт Кийосаки гарантирует: в конце вашего пути наградой станет не только финансовая свобода, но и безграничная уверенность в себе.",
      is_visible: true,
      image:
        "https://zvukislov.ru/storage/public/bookset_images/money-wallpaper-1920x1080-006.jpg",
      default_image:
        "https://zvukislov.ru/storage/public/bookset_images/money-wallpaper-1920x1080-006.jpg",
      book_count: 11,
      published_at: "2016-10-26T14:42:43Z",
      created_at: "2016-10-26T14:42:49Z",
      updated_at: "2017-11-27T10:39:34Z",
      web_url:
        "https://zvukislov.ru/booksets/69-kollektsiia-knig-biznes-guru-roberta-kiiosaki/",
    },
  ],
  is_available_for_user: false,
  is_now_playing: false,
  is_in_playlist: false,
};
