version: '3.6'
services:
#  nginx:
#    image: nginx:1.15-alpine
#    restart: unless-stopped
#    volumes:
#      - ./dev-data/nginx:/etc/nginx/conf.d
#      - ./dev-data/keys:/etc/letsencrypt
#
#    ports:
#      - "80:80"
#      - "443:443"
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  audioplayer:
    build:
      dockerfile: ./DockerfileDev
      context: ./
    command: sh -c "yarn && yarn dev"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000

    ports:
      - "3000:3000"
    working_dir: /root/front
    volumes:
      - ./:/root:cached
      - /root/node_modules


